import { IWeddingData } from "@/interfaces/IWeedingData";

export const DEFAULTDATA: IWeddingData = {
  ladiesFirst: true,
  img: "/pink-one/imgone.jpeg",
  event: [
    {
      tittle: "Akad",
      description: "Acara berlangsung siang hari menggunakan dresscode pink",
      day: "Senin",
      date: "12 September 2023",
      time: "10.00 WIB",
      placeName: "Rumah Makan Kami",
      address: "Jl. Kerja sama no 4",
      locations: "Rumah Makan Kami",
    },
    {
      tittle: "Resepsi",
      description: "Acara berlangsung siang hari menggunakan dresscode pink",
      day: "Senin",
      date: "12 September 2023",
      time: "10.00 WIB",
      placeName: "Rumah Makan Kami",
      address: "Jl. Kerja sama no 4",
      locations: "Rumah Makan Kami",
    },
    {
      tittle: "Resepsi2",
      description: "Acara berlangsung siang hari menggunakan dresscode pink",
      day: "Senin",
      date: "12 September 2023",
      time: "10.00 WIB",
      placeName: "Rumah Makan Kami",
      address: "Jl. Kerja sama no 4",
      locations: "Rumah Makan Kami",
    },
  ],
  man: {
    name: "Rama",
    fullName: "Mochamad Ramadhani",
    age: 30,
    gender: "Male",
    anak: "Putra Pertama Dari",
    bapak: "Kasimen Jiwansa",
    ibu: "Kasimun Madani",
    img: "/pink-one/man.jpg",
  },
  woman: {
    name: "Bintang",
    fullName: "Bintang Dectyanefa Putri Zafira",
    age: 30,
    gender: "Female",
    anak: "Putri Pertama Dari",
    bapak: "Kasimen Jiwansa",
    ibu: "Kasimun Madani",
    img: "/pink-one/woman.jpg",
  },
};
